In [1]:
import pandas as pd
import numpy as np

In [6]:
stocks_daily = pd.read_csv('data/gspc_daily_clean.csv')
stocks_monthly = pd.read_csv('data/gspc_monthly.csv')
stocks_monthly = pd.read_csv('data/gspc_weekly.csv')
tweet_df = pd.read_csv('data/tweet_df_cleaned.csv')

In [4]:
stocks_daily

            Date         Open        Close     Change  % Change Up/Down
0     2016-11-08  2129.919922  2139.560059   9.640137  0.004526      up
1     2016-11-09  2131.560059  2163.260010  31.699951  0.014872      up
2     2016-11-10  2167.489990  2167.479980  -0.010010 -0.000005    down
3     2016-11-11  2162.709961  2164.449951   1.739990  0.000805      up
4     2016-11-14  2165.639893  2164.199951  -1.439942 -0.000665    down
...          ...          ...          ...        ...       ...     ...
997   2020-10-26  3441.419922  3400.969971 -40.449951 -0.011754    down
998   2020-10-27  3403.149902  3390.679932 -12.469970 -0.003664    down
999   2020-10-28  3342.479980  3271.030029 -71.449951 -0.021376    down
1000  2020-10-29  3277.169922  3310.110107  32.940185  0.010051      up
1001  2020-10-30  3293.590088  3269.959961 -23.630127 -0.007175    down

[1002 rows x 6 columns]

In [9]:
tweet_df['date_only'] = pd.to_datetime(tweet_df['date']).dt.normalize()
# tweet_df.sort_values(by=['date_only'])

,Unnamed: 0,id,text,isRetweet,isDeleted,device,favorites,retweets,date,tokens,scores,scores2,avg_scores,sum_scores,date_only
0,0,98454970654916608,Republicans and Democrats have both created ou...,f,f,TweetDeck,49,255,2011-08-02 18:07:48,"['Republicans', 'Democrats', 'created', 'econo...","[('Republicans', 4.22), ('Democrats', 5.5), ('...","[4.22, 5.5, 6.06, 5.36, 2.92]",4.812000,24.06,2011-08-02
1,1,1234653427789070336,I was thrilled to be back in the Great city of...,f,f,Twitter for iPhone,73748,17404,2020-03-03 01:34:50,"['I', 'thrilled', 'back', 'Great', 'city', 'Ch...","[('I', 5.92), ('back', 5.18), ('Great', 7.88),...","[5.92, 5.18, 7.88, 5.76, 5.5, 5.52, 5.44, 6.14...",6.459091,142.10,2020-03-03
2,2,1218010753434820614,RT @CBS_Herridge: READ: Letter to surveillance...,t,f,Twitter for iPhone,0,7396,2020-01-17 03:22:47,"['RT', '@', 'CBS_Herridge', ':', 'READ', ':', ...","[('RT', 4.88), ('READ', 6.52), ('Letter', 5.94...","[4.88, 6.52, 5.94, 3.78, 6.36, 4.96, 5.6, 5.0,...",5.446667,49.02,2020-01-17
3,3,1304875170860015617,The Unsolicited Mail In Ballot Scam is a major...,f,f,Twitter for iPhone,80527,23502,2020-09-12 20:10:58,"['The', 'Unsolicited', 'Mail', 'In', 'Ballot',...","[('The', 4.98), ('Mail', 6.36), ('In', 5.5), (...","[4.98, 6.36, 5.5, 5.16, 5.76, 2.36, 6.36, 5.44...",4.902000,147.06,2020-09-12
4,4,1218159531554897920,RT @MZHemingway: Very friendly telling of even...,t,f,Twitter for iPhone,0,9081,2020-01-17 13:13:59,"['RT', '@', 'MZHemingway', ':', 'Very', 'frien...","[('RT', 4.88), ('Very', 6.12), ('friendly', 7....","[4.88, 6.12, 7.66, 5.3, 6.26, 4.94, 5.6, 5.62,...",5.765455,63.42,2020-01-17

In [16]:
tweet_df.sort_values(by=['date_only']).head(50)

,Unnamed: 0,id,text,isRetweet,isDeleted,device,favorites,retweets,date,tokens,scores,scores2,avg_scores,sum_scores,date_only
11183,11183,1698308935,Be sure to tune in and watch Donald Trump on L...,f,f,Twitter Web Client,939,519,2009-05-04 18:54:25,"['Be', 'sure', 'tune', 'watch', 'Donald', 'Tru...","[('Be', 5.68), ('sure', 6.32), ('tune', 6.18),...","[5.68, 6.32, 6.18, 5.7, 5.48, 5.3, 3.46, 6.22,...",5.774286,80.84,2009-05-04
11182,11182,1701461182,Donald Trump will be appearing on The View tom...,f,f,Twitter Web Client,259,34,2009-05-05 01:00:10,"['Donald', 'Trump', 'appearing', 'The', 'View'...","[('Donald', 5.48), ('Trump', 5.3), ('The', 4.9...","[5.48, 5.3, 4.98, 5.72, 6.18, 6.56, 5.96, 6.02...",6.182857,86.56,2009-05-05
11180,11180,1741160716,New Blog Post: Celebrity Apprentice Finale and...,f,f,Twitter Web Client,29,11,2009-05-08 20:40:15,"['New', 'Blog', 'Post', ':', 'Celebrity', 'App...","[('New', 6.82), ('Blog', 6.02), ('Post', 5.48)...","[6.82, 6.02, 5.48, 6.02, 6.0, 5.98, 6.92, 5.48...",5.994000,59.94,2009-05-08
11181,11181,1737479987,Donald Trump reads Top Ten Financial Tips on L...,f,f,Twitter Web Client,37,15,2009-05-08 13:38:08,"['Donald', 'Trump', 'reads', 'Top', 'Ten', 'Fi...","[('Donald', 5.48), ('Trump', 5.3), ('Top', 6.7...","[5.48, 5.3, 6.76, 5.44, 5.42, 6.28, 3.46, 6.24...",5.825000,69.90,2009-05-08
11178,11178,1776419923,"""Miss USA Tara Conner will not be fired - """"I'...",f,f,Twitter Web Client,25,26,2009-05-12 19:21:55,"['``', 'Miss', 'USA', 'Tara', 'Conner', 'fired...","[('Miss', 3.64), ('USA', 6.58), ('fired', 2.3)...","[3.64, 6.58, 2.3, 5.92, 6.48, 6.46, 5.38, 6.18...",5.363636,59.00,2009-05-12
11179,11179,1773561338,"""""""My persona will never be that of a wallflow...",f,f,Twitter Web Client,1877,1321,2009-05-12 14:07:28,"['``', '``', ""''"", 'My', 'persona', 'never', '...","[('My', 6.16), ('never', 3.34), ('I', 5.92), (...","[6.16, 3.34, 5.92, 4.98, 6.22, 5.26, 4.73, 5.4...",5.265556,47.39,2009-05-12
11177,11177,1786560616,Listen to an interview with Donald Trump discu...,f,f,Twitter Web Client,17,16,2009-05-13 17:38:28,"['Listen', 'interview', 'Donald', 'Trump', 'di...","[('Listen', 5.94), ('interview', 5.06), ('Dona...","[5.94, 5.06, 5.48, 5.3, 5.76, 6.82, 7.24, 6.2,...",6.156667,73.88,2009-05-13
11176,11176,1796477499,"""""""Strive for wholeness and keep your sense of...",f,f,Twitter Web Client,26,17,2009-05-14 16:30:40,"['``', '``', ""''"", 'Strive', 'wholeness', 'kee...","[('keep', 5.86), ('sense', 6.3), ('wonder', 7....","[5.86, 6.3, 7.08, 5.48, 5.3, 5.98]",6.000000,36.00,2009-05-14
11175,11175,1806258917,"""Enter the """"Think Like A Champion"""" signed bo...",f,f,Twitter Web Client,33,18,2009-05-15 14:13:13,"['``', 'Enter', '``', ""''"", 'Think', 'Like', '...","[('Enter', 5.84), ('Think', 6.2), ('Like', 7.2...","[5.84, 6.2, 7.22, 5.24, 7.64, 5.72, 7.24, 5.78...",6.317778,56.86,2009-05-15
11174,11174,1820624395,"""""""When the achiever achieves, it's not a plat...",f,f,Twitter Web Client,46,19,2009-05-16 22:22:45,"['``', '``', ""''"", 'When', 'achiever', 'achiev...","[('When', 4.96), (""'s"", 4.94), ('beginning', 6...","[4.96, 4.94, 6.04, 5.48, 5.3, 5.98]",5.450000,32.70,2009-05-16
11173,11173,1826225450,"""""""Don’t be afraid of being unique - it's like...",f,f,Twitter Web Client,123,56,2009-05-17 15:00:03,"['``', '``', ""''"", 'Don', '’', 'afraid', 'uniq...","[('Don', 4.98), ('afraid', 2.66), ('unique', 6...","[4.98, 2.66, 6.98, 4.94, 7.22, 2.66, 7.18, 6.2...",5.420000,59.62,2009-05-17
11172,11172,1836131903,"""""""We win in our lives by having a champion's ...",f,f,Twitter Web Client,142,83,2009-05-18 14:26:00,"['``', '``', ""''"", 'We', 'win', 'lives', 'cham...","[('We', 6.38), ('win', 8.12), ('lives', 6.22),...","[6.38, 8.12, 6.22, 7.64, 4.94, 5.72, 5.68, 5.4...",6.146000,61.46,2009-05-18
11171,11171,1849558306,"""""""...these days...we could all use a little o...",f,f,Twitter Web Client,22,23,2009-05-19 17:43:39,"['``', '``', ""''"", '...', 'days', '...', 'coul...","[('days', 5.76), ('could', 5.52), ('use', 5.64...","[5.76, 5.52, 5.64, 4.6, 6.68, 6.28, 5.98]",5.780000,40.46,2009-05-19
11170,11170,1859044981,"""""""Always know you could be on the precipice o...",f,f,Twitter Web Client,61,32,2009-05-20 13:25:39,"['``', '``', ""''"", 'Always', 'know', 'could', ...","[('Always', 6.48), ('know', 6.1), ('could', 5....","[6.48, 6.1, 5.52, 5.0, 7.88, 5.48, 5.3, 5.98]",5.967500,47.74,2009-05-20
11169,11169,1864367186,Read a great interview with Donald Trump that ...,f,f,Twitter Web Client,14,10,2009-05-20 22:29:47,"['Read', 'great', 'interview', 'Donald', 'Trum...","[('Read', 6.52), ('great', 7.88), ('interview'...","[6.52, 7.88, 5.06, 5.48, 5.3, 5.46, 4.98, 6.82...",5.881667,70.58,2009-05-20
11168,11168,1878373267,"""""""Keep it fast, short and direct - whatever i...",f,f,Twitter Web Client,91,62,2009-05-22 02:59:39,"['``', '``', ""''"", 'Keep', 'fast', ',', 'short...","[('Keep', 5.86), ('fast', 6.44), ('short', 4.4...","[5.86, 6.44, 4.46, 5.68, 4.58, 5.48, 5.3, 5.98]",5.472500,43.78,2009-05-22
11167,11167,1884022748,"""Don't forget to enter the """"Think Like A Cham...",f,f,Twitter Web Client,28,18,2009-05-22 16:28:34,"['``', 'Do', ""n't"", 'forget', 'enter', '``', ""...","[('Do', 5.76), ('forget', 3.22), ('enter', 5.8...","[5.76, 3.22, 5.84, 6.2, 7.22, 5.24, 7.64, 5.72...",5.985455,65.84,2009-05-22
11166,11166,1894284587,Did you know Donald Trump is on Facebook? http...,f,f,Twitter Web Client,89,71,2009-05-23 16:11:19,"['Did', 'know', 'Donald', 'Trump', 'Facebook',...","[('Did', 5.58), ('know', 6.1), ('Donald', 5.48...","[5.58, 6.1, 5.48, 5.3, 6.08, 5.98, 5.7, 6.66, ...",5.900000,53.10,2009-05-23
11165,11165,1924074459,"""""""Your higher self is in direct opposition to...",f,f,Twitter Web Client,90,49,2009-05-26 14:42:01,"['``', '``', ""''"", 'Your', 'higher', 'self', '...","[('Your', 5.6), ('higher', 6.46), ('self', 6.2...","[5.6, 6.46, 6.24, 5.68, 3.48, 7.5, 5.32, 5.48,...",5.704000,57.04,2009-05-26
11120,11120,1936022874,Read an excerpt from Think Like A Champion by ...,f,f,Twitter Web Client,38,10,2009-05-27 14:18:52,"['Read', 'excerpt', 'Think', 'Like', 'A', 'Cha...","[('Read', 6.52), ('Think', 6.2), ('Like', 7.22...","[6.52, 6.2, 7.22, 5.24, 7.64, 5.48, 5.3, 5.98]",6.197500,49.58,2009-05-27
11130,11130,1949899014,"""""""You have to know when to call it quits and ...",f,f,Twitter Web Client,59,60,2009-05-28 18:03:34,"['``', '``', ""''"", 'You', 'know', 'call', 'qui...","[('You', 6.24), ('know', 6.1), ('call', 5.74),...","[6.24, 6.1, 5.74, 5.86, 5.36, 6.1, 5.48, 5.3, ...",5.795556,52.16,2009-05-28
11164,11164,2019316195,Check out Donald Trump's new iGoogle Showcase ...,f,f,Twitter Web Client,20,14,2009-06-03 18:19:49,"['Check', 'Donald', 'Trump', ""'s"", 'new', 'iGo...","[('Check', 6.1), ('Donald', 5.48), ('Trump', 5...","[6.1, 5.48, 5.3, 4.94, 6.82, 5.62, 5.98]",5.748571,40.24,2009-06-03
11163,11163,2045871770,"“If you don't have problems, you're pretending...",f,f,Twitter Web Client,33,15,2009-06-05 18:21:37,"['“', 'If', ""n't"", 'problems', ',', ""'re"", 'pr...","[('If', 4.66), ('problems', 2.92), ('pretendin...","[4.66, 2.92, 4.92, 5.48, 5.3, 5.98]",4.876667,29.26,2009-06-05
11162,11162,2080633709,"""Last week to enter the """"Think Like A Champio...",f,f,Twitter Web Client,4,11,2009-06-08 20:15:29,"['``', 'Last', 'week', 'enter', '``', ""''"", 'T...","[('Last', 3.74), ('week', 5.08), ('enter', 5.8...","[3.74, 5.08, 5.84, 6.2, 7.22, 5.24, 7.64, 5.72...",5.970909,65.68,2009-06-08
11161,11161,2165353946,Today is Donald Trump's Birthday! Send him you...,f,f,Twitter Web Client,32,27,2009-06-14 14:25:36,"['Today', 'Donald', 'Trump', ""'s"", 'Birthday',...","[('Today', 6.22), ('Donald', 5.48), ('Trump', ...","[6.22, 5.48, 5.3, 4.94, 7.78, 5.38, 7.2, 5.98]",6.035000,48.28,2009-06-14
11160,11160,2184650461,Thanks to all for your thoughtful birthday wis...,f,f,Twitter Web Client,37,37,2009-06-15 23:13:05,"['Thanks', 'thoughtful', 'birthday', 'wishes',...","[('Thanks', 7.4), ('birthday', 7.78), ('wishes...","[7.4, 7.78, 7.2, 5.48, 5.3]",6.632000,33.16,2009-06-15
11159,11159,2222067805,"""RE: FB Vanity URLs: SF Chronicle - """"David Be...",f,f,Twitter Web Client,17,18,2009-06-18 13:26:53,"['``', 'RE', ':', 'FB', 'Vanity', 'URLs', ':',...","[('RE', 4.88), ('FB', 5.48), ('SF', 5.24), ('C...","[4.88, 5.48, 5.24, 5.46, 5.5, 5.4, 6.82, 5.48,...",5.531667,66.38,2009-06-18
11158,11158,2266041769,- Wishing a Happy Father's Day to all the Dad'...,f,f,Twitter Web Client,189,84,2009-06-21 14:47:41,"['-', 'Wishing', 'Happy', 'Father', ""'s"", 'Day...","[('Wishing', 6.74), ('Happy', 8.3), ('Father',...","[6.74, 8.3, 7.06, 4.94, 6.24, 7.02, 4.94, 6.24...",6.421667,77.06,2009-06-21
11009,11009,2294519255,“Expand your life every day.” –Donald J. Trump...,f,f,Twitter Web Client,40,19,2009-06-23 13:40:38,"['“', 'Expand', 'life', 'every', 'day.', '”', ...","[('Expand', 6.04), ('life', 7.32), ('every', 5...","[6.04, 7.32, 5.64, 5.3, 5.98]",6.056000,30.28,2009-06-23
10910,10910,2317112756,Donald Trump’s commercial-free WWE Raw does bi...,f,f,Twitter Web Client,19,29,2009-06-24 22:09:19,"['Donald', 'Trump', '’', 'commercial-free', 'W...","[('Donald', 5.48), ('Trump', 5.3), ('Raw', 4.2...","[5.48, 5.3, 4.24, 6.22, 5.54, 5.98]",5.460000,32.76,2009-06-24
11156,11156,2346367430,"""RE: Michael Jackson: """"He was a great friend ...",f,f,Twitter Web Client,310,119,2009-06-26 16:51:16,"['``', 'RE', ':', 'Michael', 'Jackson', ':', '...","[('RE', 4.88), ('Michael', 5.7), ('Jackson', 5...","[4.88, 5.7, 5.7, 5.42, 7.88, 7.66, 5.02, 2.56,...",5.568889,50.12,2009-06-26
11155,11155,2403435685,Watch a powerful and frank interview with Dona...,f,f,Twitter Web Client,11,5,2009-06-30 13:32:59,"['Watch', 'powerful', 'frank', 'interview', 'D...","[('Watch', 5.7), ('powerful', 7.08), ('frank',...","[5.7, 7.08, 5.94, 5.06, 5.48, 5.3, 4.38, 5.2, ...",5.490769,71.38,2009-06-30
11154,11154,2475429091,Here's to a safe and happy Independence Day fo...,f,f,Twitter Web Client,81,40,2009-07-04 23:19:56,"['Here', ""'s"", 'safe', 'happy', 'Independence'...","[('Here', 5.48), (""'s"", 4.94), ('safe', 7.04),...","[5.48, 4.94, 7.04, 8.3, 7.28, 6.24, 5.4, 7.66,...",6.312000,63.12,2009-07-04
11153,11153,2614325575,"""""""Be aware of things that seem inexplicable b...",f,f,Twitter Web Client,32,19,2009-07-13 14:03:38,"['``', '``', ""''"", 'Be', 'aware', 'things', 's...","[('Be', 5.68), ('aware', 5.78), ('things', 5.7...","[5.68, 5.78, 5.76, 5.24, 6.22, 5.32, 5.72, 5.4...",5.648000,56.48,2009-07-13
11152,11152,2650952843,Donald Trump backs 'Apprentice' Randal Pinkett...,f,f,Twitter Web Client,46,9,2009-07-15 13:40:35,"['Donald', 'Trump', 'backs', ""'Apprentice"", ""'...","[('Donald', 5.48), ('Trump', 5.3), ('backs', 5...","[5.48, 5.3, 5.34, 5.24, 5.14, 5.98]",5.413333,32.48,2009-07-15
11151,11151,2779566791,"""Congrats to winners from around the world who...",f,f,Twitter Web Client,16,11,2009-07-22 15:32:52,"['``', 'Congrats', 'winners', 'around', 'world...","[('Congrats', 7.5), ('winners', 7.62), ('aroun...","[7.5, 7.62, 5.62, 6.52, 5.82, 6.2, 7.22, 5.24,...",6.405000,76.86,2009-07-22
11150,11150,2891870497,Check out a list of Donald Trump's books for s...,f,f,Twitter Web Client,26,31,2009-07-28 15:50:31,"['Check', 'list', 'Donald', 'Trump', ""'s"", 'bo...","[('Check', 6.1), ('list', 5.46), ('Donald', 5....","[6.1, 5.46, 5.48, 5.3, 4.94, 7.28, 6.4, 6.78, ...",5.981667,71.78,2009-07-28
11149,11149,3124382438,Browse Donald Trump's Summer Reading List for ...,f,f,Twitter Web Client,17,33,2009-08-04 13:50:58,"['Browse', 'Donald', 'Trump', ""'s"", 'Summer', ...","[('Donald', 5.48), ('Trump', 5.3), (""'s"", 4.94...","[5.48, 5.3, 4.94, 6.4, 6.78, 5.46, 5.94, 7.86,...",6.016667,72.20,2009-08-04
11148,11148,3246382217,"""""""Think. That’s the first step. Use all your ...",f,f,Twitter Web Client,68,42,2009-08-11 14:50:47,"['``', '``', ""''"", 'Think', '.', 'That', '’', ...","[('Think', 6.2), ('That', 4.94), ('first', 6.8...","[6.2, 4.94, 6.82, 5.32, 5.64, 6.68, 6.26, 5.48...",5.862000,58.62,2009-08-11
11147,11147,3308367056,Ivanka is now on Twitter - You can follow her ...,f,f,Twitter Web Client,52,38,2009-08-14 14:33:46,"['Ivanka', 'Twitter', '-', 'You', 'follow', '@...","[('Twitter', 5.46), ('You', 6.24), ('follow', ...","[5.46, 6.24, 5.66, 5.82, 6.96, 8.0]",6.356667,38.14,2009-08-14
11146,11146,3427503309,-- Watch Donald Trump's recent appearance on T...,f,f,Twitter Web Client,35,6,2009-08-20 13:43:22,"['--', 'Watch', 'Donald', 'Trump', ""'s"", 'rece...","[('Watch', 5.7), ('Donald', 5.48), ('Trump', 5...","[5.7, 5.48, 5.3, 4.94, 5.56, 5.8, 4.98, 3.46, ...",5.358182,58.94,2009-08-20
11145,11145,3450626731,Watch the Miss Universe competition LIVE from ...,f,f,Twitter Web Client,13,14,2009-08-21 14:32:45,"['Watch', 'Miss', 'Universe', 'competition', '...","[('Watch', 5.7), ('Miss', 3.64), ('Universe', ...","[5.7, 3.64, 6.84, 5.64, 6.84, 7.28, 5.72, 5.1,...",5.826000,58.26,2009-08-21
11144,11144,3498743628,Reminder: The Miss Universe competition will b...,f,f,Twitter Web Client,12,10,2009-08-23 21:12:37,"['Reminder', ':', 'The', 'Miss', 'Universe', '...","[('Reminder', 5.54), ('The', 4.98), ('Miss', 3...","[5.54, 4.98, 3.64, 6.84, 5.64, 6.84, 6.14, 5.7...",5.607273,61.68,2009-08-23
11143,11143,3627328938,- Donald Trump bids to buy the Oreo Double Stu...,f,f,Twitter Web Client,357,244,2009-08-29 16:23:56,"['-', 'Donald', 'Trump', 'bids', 'buy', 'Oreo'...","[('Donald', 5.48), ('Trump', 5.3), ('buy', 6.2...","[5.48, 5.3, 6.28, 5.8, 6.06, 5.8, 6.1, 5.98]",5.850000,46.80,2009-08-29
11142,11142,3688564134,"""- More hysterical DSRL videos featuring Donal...",f,f,Twitter Web Client,56,57,2009-09-01 13:55:34,"['``', '-', 'More', 'hysterical', 'DSRL', 'vid...","[('More', 6.24), ('videos', 6.52), ('featuring...","[6.24, 6.52, 5.78, 5.48, 5.3, 5.8, 5.3, 6.76, ...",5.958462,77.46,2009-09-01
11141,11141,3982428551,Read Donald Trump's Top Ten Tips for Success: ...,f,f,Twitter Web Client,35,31,2009-09-14 15:50:14,"['Read', 'Donald', 'Trump', ""'s"", 'Top', 'Ten'...","[('Read', 6.52), ('Donald', 5.48), ('Trump', 5...","[6.52, 5.48, 5.3, 4.94, 6.76, 5.44, 6.28, 7.86...",6.062222,54.56,2009-09-14
11140,11140,4472353826,"""""""A lot of people have imagination, but can't...",f,f,Twitter Web Client,138,74,2009-09-29 15:28:23,"['``', '``', ""''"", 'A', 'lot', 'people', 'imag...","[('A', 5.24), ('lot', 5.78), ('people', 6.16),...","[5.24, 5.78, 6.16, 6.96, 5.1, 6.96, 5.48, 5.3,...",5.884444,52.96,2009-09-29
11139,11139,4629116949,- Read what Donald Trump has to say about daug...,f,f,Twitter Web Client,14,10,2009-10-05 14:37:38,"['-', 'Read', 'Donald', 'Trump', 'say', 'daugh...","[('Read', 6.52), ('Donald', 5.48), ('Trump', 5...","[6.52, 5.48, 5.3, 5.54, 7.04, 4.94, 6.26, 6.82...",5.932308,77.12,2009-10-05
11138,11138,4862580190,Watch video of Ivanka Trump sharing business a...,f,f,Twitter Web Client,19,12,2009-10-14 14:13:17,"['Watch', 'video', 'Ivanka', 'Trump', 'sharing...","[('Watch', 5.7), ('video', 6.48), ('Trump', 5....","[5.7, 6.48, 5.3, 7.06, 5.94, 6.22, 7.12, 5.98]",6.225000,49.80,2009-10-14
11137,11137,5069623974,"Hear Donald Trump discuss big gov spending, ba...",f,f,Twitter Web Client,28,7,2009-10-22 13:57:04,"['Hear', 'Donald', 'Trump', 'discuss', 'big', ...","[('Hear', 5.84), ('Donald', 5.48), ('Trump', 5...","[5.84, 5.48, 5.3, 5.96, 6.22, 4.62, 5.24, 5.92...",5.448333,65.38,2009-10-22

In [17]:
tweet_groupby_sum = tweet_df.groupby(['date_only']).sum

In [14]:
test = pd.dataFrame()

,Unnamed: 0,id,favorites,retweets,avg_scores,sum_scores
date_only,,,,,,
2009-05-04,11183.0,1.698309e+09,939.0,519.0,5.774286,80.84
2009-05-05,11182.0,1.701461e+09,259.0,34.0,6.182857,86.56
2009-05-08,22361.0,3.478641e+09,66.0,26.0,11.819000,129.84
2009-05-12,22357.0,3.549981e+09,1902.0,1347.0,10.629192,106.39
2009-05-13,11177.0,1.786561e+09,17.0,16.0,6.156667,73.88
...,...,...,...,...,...,...
2020-10-20,71194.0,1.054886e+19,1293019.0,301467.0,39.682155,421.14
2020-10-21,165802.0,4.880150e+19,2554907.0,646224.0,176.394976,2379.17
2020-10-22,248590.0,3.429949e+19,3209931.0,681597.0,145.166895,2050.85
2020-10-23,182094.0,6.333900e+19,3068584.0,1115660.0,211.275864,1906.58
2020-10-24,32462.0,6.467910e+19,2446506.0,727702.0,240.414866,2430.68

In [19]:
combined_daily_df = pd.merge(tweet_groupby_sum, stocks_daily, left_on='date_only', right_on='Date')

TypeError: Can only merge Series or DataFrame objects, a <class 'method'> was passed

In [11]:
combined_daily_df = pd.concat(tweet_df, stocks_daily, left_on='date_only', right_on='Date')

TypeError: concat() got an unexpected keyword argument 'left_on'